name: Build and Release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*' # Triggers on tag pushes like v1.0.0

jobs:
  build:
    name: Build and Publish for Windows, macOS, and Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rtid: linux-x64
            ext: ""
          - os: windows-latest
            rtid: win-x64
            ext: ".exe"
          - os: macos-latest
            rtid: osx-x64
            ext: ""

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Build the application
      - name: Build Application
        run: dotnet publish GithubChangelog.csproj -c Release -r ${{ matrix.rtid }} --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true
        shell: bash

      # Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: bin/Release/net7.0/${{ matrix.rtid }}/publish/*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Download build artifacts for Linux
      - name: Download Linux Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-ubuntu-latest
          path: ./artifacts/linux

      # Download build artifacts for Windows
      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-windows-latest
          path: ./artifacts/windows

      # Download build artifacts for macOS
      - name: Download macOS Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-macos-latest
          path: ./artifacts/macos

      # Create GitHub Release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload release assets
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ./artifacts/linux/*
            ./artifacts/windows/*
            ./artifacts/macos/*
          tag: ${{ github.ref_name }}
